const MODIFY_CARD_NAME = "MODIFY_CARD_NAME";
const MODIFY_CARD_NUMBER = "MODIFY_CARD_NUMBER";
const MODIFY_EXPIRE_MONTH = "MODIFY_EXPIRE_MONTH";
const MODIFY_EXPIRE_YEAR = "MODIFY_EXPIRE_YEAR";
const MODIFY_CVV = "MODIFY_CVV";
const FLIP_CARD = "FLIP_CARD";
const FLIP_CARD_BACK = "FLIP_CARD_BACK";

export default { 
        MODIFY_CARD_NAME, 
        MODIFY_CARD_NUMBER,
        MODIFY_EXPIRE_MONTH,
        MODIFY_EXPIRE_YEAR,
        MODIFY_CVV,
        FLIP_CARD,
        FLIP_CARD_BACK
    }